// src/frontend/poke-query/src/lib/ItemCard.svelte
<script>
  export let data;
</script>

<div class="card mw-20 h-50 m-2 card-item">
  <img
    class="card-img-top h-25  pt-2 ps-5 pe-5"
    src={data.json.Sprites.Default}
    alt={data.name}
  />
  <div class="card-body">
    <h4 class="card-title text-capitalize text-center">
      {data.json.Name.replaceAll("-", " ")}
    </h4>
    {#if typeof data.json.EffectEntries[0] !== "undefined"}
      <p class="card-text text-wrap">
        {data.json.EffectEntries[0].ShortEffect}
      </p>
    {/if}
  </div>
</div>

<style>
  .card-item {
    border-color: #ecf296;
    border-width: 0.35em;
    width: 15rem;
  }
</style>

// src/frontend/poke-query/poke-query-react/src/components/ItemCard.tsx
import React from 'react';

interface ItemCardProps {
  data: any;
}

const ItemCard: React.FC<ItemCardProps> = ({ data }) => {
  // Fix sprite URL if needed
  const spriteUrl = data.sprites?.default?.replace(
    'https://raw.githubusercontent.com/PokeAPI/sprites/master/https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites',
    'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites'
  );

  return (
    <div className="card mw-20 m-2 border-4 border-[#ecf296] w-60 h-[21rem]">
      <img
        className="card-img-top h-[35%] pt-2 ps-5 pe-5 mx-auto"
        src={spriteUrl}
        alt={data.name}
      />
      <div className="card-body p-4">
        <h4 className="card-title text-capitalize text-center text-lg font-bold">
          {data.name?.replaceAll('-', ' ')}
        </h4>
        {data.effect_entries && data.effect_entries[0] && (
          <p className="card-text text-wrap text-sm mt-2">
            {data.effect_entries[0].short_effect}
          </p>
        )}
      </div>
    </div>
  );
};

export default ItemCard;
