// src/frontend/poke-query/src/App.svelte
<script lang="ts">
  import ItemCard from "./lib/components/cards/ItemCard.svelte";
  import MoveCard from "./lib/components/cards/MoveCard.svelte";
  import PokemonCard from "./lib/components/cards/PokemonCard.svelte";
import { isLoadingSessionData, loadSessionData } from "./lib/data/session";

  enum ResourceTypes {
    Pokemon = 0,
    Moves = 1,
    Items = 2,
  }

  let results: any[] = [];
  let query: string;
  let baseUri: string = process.env.API_BASE_URI;

  let isLoading: boolean = false;

  let includePokemon: boolean = true;
  let includeItems: boolean = false;
  let includeMoves: boolean = false;

  const handleKeyDown = (event): void => {
    if (event.keyCode === 13) {
      handleSearch();
    }
  };

  const handleSearch = async () => {
    results = [];

    if (isLoadingSessionData)
      return;

    if (query === null || typeof query === "undefined" || query === "") {
      return;
    }

    isLoading = true;

    let requestUri: string = `${baseUri}/query`;
    let requestBody = {
      Query: query,
      IncludePokemon: includePokemon,
      IncludeItems: includeItems,
      IncludeMoves: includeMoves,
    };

    await fetch(requestUri, {
      method: "POST",
      headers: {
        Accept: "application/json",
        "Content-Type": "application/json",
      },
      body: JSON.stringify(requestBody),
    })
      .then((r) => {
        if (!r.ok) {
          isLoading = false;
          throw new Error("API FAILED TO RETURN 200 OK");
        }
        return r.json();
      })
      .then((data) => {
        results = data;
        results.forEach((x) => (x.json = JSON.parse(x.json)));
      });

    isLoading = false;
    console.log(results);
  };
</script>

<div class="container-fluid my-3">
  <h1 class="row mb-3 justify-content-center">PokeQuery</h1>
  <div class="row justify-content-center">
    <div class="col col-lg-3">
      <input
        type="text"
        class="form-control form-control-lg"
        placeholder="pikachu, leftovers, etc..."
        bind:value={query}
        minlength="1"
      />
    </div>
    <div class="col-auto">
      <button
        type="submit"
        class="btn btn-primary btn-lg mb-3"
        on:click={handleSearch}>
        {#await loadSessionData(baseUri)}
          <div class="spinner-border" role="status">
            <span class="visually-hidden">Loading...</span>
          </div>
        {:then}
          Search 🔎
        {/await}
        </button
      >
    </div>
    <div class="form-check d-flex justify-content-center">
      <div class="form-check form-check-inline">
        <input
          class="form-check-input"
          id="cbPkmn"
          type="checkbox"
          bind:checked={includePokemon}
        />
        <label class="form-check-label" for="cbPkmn">Pokemon</label>
      </div>
      <div class="form-check form-check-inline">
        <input
          class="form-check-input"
          id="cbItems"
          type="checkbox"
          bind:checked={includeItems}
        />
        <label class="form-check-label" for="cbItems">Items</label>
      </div>
      <div class="form-check form-check-inline">
        <input
          class="form-check-input"
          id="cbMoves"
          type="checkbox"
          bind:checked={includeMoves}
        />
        <label class="form-check-label" for="cbMoves">Moves</label>
      </div>
    </div>
  </div>

  <div class="container mt-3 d-flex flex-wrap justify-content-center">
    {#if isLoading}
      <div class="spinner-border" role="status">
        <span class="visually-hidden">Loading...</span>
      </div>
    {/if}

    {#each results as result}
      {#if result.resourceType === ResourceTypes.Pokemon && result.json.IsDefault === true}
        <PokemonCard data={result} />
      {:else if result.resourceType === ResourceTypes.Items && !result.name.includes("-candy")}
        <ItemCard data={result} />
      {:else if result.resourceType === ResourceTypes.Moves}
        <MoveCard data={result} />
      {/if}
    {/each}
  </div>
</div>

<svelte:window on:keydown={handleKeyDown} />

// src/frontend/poke-query/poke-query-react/src/App.tsx

import React, { useState, useEffect } from 'react';
import { loadSessionData } from './sessionData';
import PokemonCard from './components/PokemonCard';
import ItemCard from './components/ItemCard';
import MoveCard from './components/MoveCard';
import NatureCard from './components/NatureCard';

const API_BASE_URI = import.meta.env.VITE_API_BASE_URI || '';

const App: React.FC = () => {
  const [query, setQuery] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [pkmnResults, setPkmnResults] = useState<any[]>([]);
  const [itemResults, setItemResults] = useState<any[]>([]);
  const [moveResults, setMoveResults] = useState<any[]>([]);
  const [natureResults, setNatureResults] = useState<any[]>([]);
  const [includePokemon, setIncludePokemon] = useState(true);
  const [includeItems, setIncludeItems] = useState(false);
  const [includeMoves, setIncludeMoves] = useState(false);
  const [includeNatures, setIncludeNatures] = useState(false);

  const handleQuery = async (prefix: string, flag: boolean) => {
    if (!flag) return [];
    const res = await fetch(`${API_BASE_URI}/search/${prefix}/${query}`, {
      method: 'GET',
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json',
      },
    });
    if (!res.ok) throw new Error('API FAILED TO RETURN 200 OK ON /search');
    const data = await res.json();
    return data.map((x: string) => JSON.parse(x));
  };

  const handleSearch = async () => {
    if (!query) return;
    setIsLoading(true);
    setPkmnResults([]);
    setItemResults([]);
    setMoveResults([]);
    setNatureResults([]);
    try {
      const [pkmn, items, moves, natures] = await Promise.all([
        handleQuery('pokemon', includePokemon),
        handleQuery('item', includeItems),
        handleQuery('move', includeMoves),
        handleQuery('nature', includeNatures),
      ]);
      setPkmnResults(pkmn.sort((a: any, b: any) => a.id - b.id));
      setItemResults(items);
      setMoveResults(moves);
      setNatureResults(natures);
    } catch (e) {
      // handle error
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    // Load session data on app mount (only once)
    loadSessionData(API_BASE_URI);
  }, []);

  useEffect(() => {
    const handleKeyDown = (event: KeyboardEvent) => {
      if (event.key === 'Enter') {
        handleSearch();
      }
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [query, includePokemon, includeItems, includeMoves, includeNatures]);

  return (
    <div className="container-fluid my-3">
      <h1 className="row mb-3 justify-content-center">PokeQuery</h1>
      <div className="row d-flex justify-content-center mb-4 align-items-center">
        <div className="col col-lg-3">
          <input
            type="text"
            className="form-control form-control-lg"
            style={{ minWidth: '300px', maxWidth: '400px' }}
            placeholder="pikachu, leftovers, etc..."
            value={query}
            onChange={e => setQuery(e.target.value)}
            minLength={1}
          />
        </div>
        <div className="col-auto">
          <button
            type="submit"
            className="btn btn-primary btn-lg"
            style={{ marginLeft: 0 }}
            onClick={handleSearch}
          >
            {isLoading ? (
              <span className="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
            ) : (
              <>Search 🔎</>
            )}
          </button>
        </div>
      </div>
      <div className="d-flex justify-content-center mb-4">
        <div className="form-check form-check-inline">
          <input className="form-check-input" type="checkbox" checked={includePokemon} onChange={e => setIncludePokemon(e.target.checked)} id="cbPkmn" />
          <label className="form-check-label" htmlFor="cbPkmn">Pokemon</label>
        </div>
        <div className="form-check form-check-inline">
          <input className="form-check-input" type="checkbox" checked={includeItems} onChange={e => setIncludeItems(e.target.checked)} id="cbItems" />
          <label className="form-check-label" htmlFor="cbItems">Items</label>
        </div>
        <div className="form-check form-check-inline">
          <input className="form-check-input" type="checkbox" checked={includeMoves} onChange={e => setIncludeMoves(e.target.checked)} id="cbMoves" />
          <label className="form-check-label" htmlFor="cbMoves">Moves</label>
        </div>
        <div className="form-check form-check-inline">
          <input className="form-check-input" type="checkbox" checked={includeNatures} onChange={e => setIncludeNatures(e.target.checked)} id="cbNatures" />
          <label className="form-check-label" htmlFor="cbNatures">Natures</label>
        </div>
      </div>
      <div className="container mt-3 d-flex flex-wrap justify-content-center">
        {isLoading ? (
          <span className="spinner-border text-primary" style={{ fontSize: '2rem' }} role="status"></span>
        ) : (
          <>
            {[...pkmnResults.filter(x => x.is_default),
              ...itemResults.filter(x => !x.name.includes('-candy')),
              ...moveResults,
              ...natureResults].slice(0, 12).map((result, idx) => {
              let CardComponent;
              if (result.types) CardComponent = PokemonCard;
              else if (result.power !== undefined || result.accuracy !== undefined || result.pp !== undefined) CardComponent = MoveCard;
              else if (result.increased_stat !== undefined || result.decreased_stat !== undefined) CardComponent = NatureCard;
              else if (result.effect_entries) CardComponent = ItemCard;
              else return null;
              return (
                <CardComponent data={result} key={result.id || idx} />
              );
            })}
          </>
        )}
      </div>
    </div>
  );

}
export default App;
