// src/frontend/poke-query/src/lib/components/modals/TypeModal.svelte
<script>
    import TypeChiclet from "../TypeChiclet.svelte";

  export let pkmnType;
  
  let typeName = pkmnType.name;
  let modalName = `typeModal-${typeName}`;
  let typeData = JSON.parse(sessionStorage.typeData);

    for (let i = 0; i < typeData.length; i++) {
      typeData[i] = JSON.parse(typeData[i]);
    }

  let damageRelations = typeData.find(x => x.name === typeName).damage_relations;
</script>

<!-- Button trigger modal -->
    <TypeChiclet typeName={typeName} isStatic={false} />
  
      <!-- Modal -->
  <div class="modal fade" id="{modalName}" tabindex="-1" aria-labelledby="{modalName}-Label" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
      <div class="modal-content">
        <div class="modal-header">
          <h6 class="modal-title text-capitalize" id="{modalName}-Label">Type: {typeName}</h6>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <div class="container px-5">
            <div class="container title-border">
                <h4>Offensive</h4>
                {#if damageRelations.double_damage_to.length > 0}
                <h6>Strong Against:</h6>
                <div class="d-flex flex-wrap justify-content-center">
                    {#each damageRelations.double_damage_to as type}
                        <TypeChiclet typeName={type.name} isStatic={true} />
                    {/each}
                </div>
                {/if}
                {#if damageRelations.half_damage_to.length > 0}
                <h6>Weak Against:</h6>
                <div class="d-flex flex-wrap justify-content-center">
                    {#each damageRelations.half_damage_to as type}
                        <TypeChiclet typeName={type.name} isStatic={true} />
                    {/each}
                </div>
                {/if}
                {#if damageRelations.no_damage_to.length > 0}
                <h6>Resisted By:</h6>
                <div class="d-flex flex-wrap justify-content-center">
                    {#each damageRelations.no_damage_to as type}
                        <TypeChiclet typeName={type.name} isStatic={true} />
                    {/each}
                </div>
                {/if}
            </div>
            <div class="container title-border">
                <h4>Defensive</h4>
                {#if damageRelations.half_damage_from.length > 0}
                <h6>Strong Against:</h6>
                <div class="d-flex flex-wrap justify-content-center">
                    {#each damageRelations.half_damage_from as type}
                        <TypeChiclet typeName={type.name} isStatic={true} />
                    {/each}
                </div>
                {/if}
                {#if damageRelations.double_damage_from.length > 0}
                <h6>Weak Against:</h6>
                <div class="d-flex flex-wrap justify-content-center">
                    {#each damageRelations.double_damage_from as type}
                        <TypeChiclet typeName={type.name} isStatic={true} />
                    {/each}
                </div>
                {/if}
                {#if damageRelations.no_damage_from.length > 0}
                <h6>Immune To:</h6>
                <div class="d-flex flex-wrap justify-content-center">
                    {#each damageRelations.no_damage_from as type}
                        <TypeChiclet typeName={type.name} isStatic={true} />
                    {/each}
                </div>
                {/if}
            </div>

          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>

  <style>
    .title-border {
        border: 1px solid black;
        margin-bottom: 1rem;
        padding: 1rem;
    }

    .title-border h4 {
        margin-top: -2rem;
        margin-left: 10px;
        padding-left: 1rem;
        background-color: white;
        display: block;
        width: 130px;
    }
  </style>

// src/frontend/poke-query/src/components/TypeModal.tsx
import React, { useMemo } from 'react';
import TypeChiclet from './TypeChiclet';

interface TypeModalProps {
  pkmnType: any;
}

const TypeModal: React.FC<TypeModalProps> = ({ pkmnType }) => {
  const typeName = pkmnType?.name || '';
  const modalName = `typeModal-${typeName}`;
  const modalLabel = `${modalName}-Label`;
  const typeData = useMemo(() => {
    try {
      const raw = sessionStorage.getItem('typeData');
      if (!raw) return [];
      const arr = JSON.parse(raw);
      return arr.map((x: string) => typeof x === 'string' ? JSON.parse(x) : x);
    } catch {
      return [];
    }
  }, []);
  const damageRelations = useMemo(() => {
    return typeData.find((x: any) => x.name === typeName)?.damage_relations || {};
  }, [typeData, typeName]);

  // Helper for each damage relation type
  const renderTypeRow = (label: string, arr: any[] = []) =>
    arr.length > 0 && (
      <>
        <h6>{label}</h6>
        <div className="d-flex flex-wrap justify-content-center mb-2">
          {arr.map((type, i) => (
            <TypeChiclet key={type.name + i} typeName={type.name} isStatic={true} />
          ))}
        </div>
      </>
    );

  return (
    <>
      {/* Button trigger modal */}
      <button
        type="button"
        className="btn btn-link p-0 border-0 align-baseline"
        data-bs-toggle="modal"
        data-bs-target={`#${modalName}`}
        style={{ textDecoration: 'none' }}
      >
        <TypeChiclet typeName={typeName} isStatic={false} />
      </button>

      {/* Modal */}
      <div className="modal fade" id={modalName} tabIndex={-1} aria-labelledby={modalLabel} aria-hidden="true">
        <div className="modal-dialog modal-dialog-centered modal-dialog-scrollable">
          <div className="modal-content">
            <div className="modal-header">
              <h6 className="modal-title text-capitalize" id={modalLabel}>Type: {typeName}</h6>
              <button type="button" className="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div className="modal-body">
              <div className="container px-3">
                <div className="container title-border mb-3 p-3">
                  <h4>Offensive</h4>
                  {renderTypeRow('Strong Against:', damageRelations.double_damage_to)}
                  {renderTypeRow('Weak Against:', damageRelations.half_damage_to)}
                  {renderTypeRow('Resisted By:', damageRelations.no_damage_to)}
                </div>
                <div className="container title-border mb-3 p-3">
                  <h4>Defensive</h4>
                  {renderTypeRow('Strong Against:', damageRelations.half_damage_from)}
                  {renderTypeRow('Weak Against:', damageRelations.double_damage_from)}
                  {renderTypeRow('Immune To:', damageRelations.no_damage_from)}
                </div>
              </div>
            </div>
            <div className="modal-footer">
              <button type="button" className="btn btn-primary" data-bs-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
      </div>
      <style>{`
        .title-border {
          border: 1px solid black;
          margin-bottom: 1rem;
          padding: 1rem;
        }
        .title-border h4 {
          margin-top: -2rem;
          margin-left: 10px;
          padding-left: 1rem;
          background-color: white;
          display: block;
          width: 130px;
        }
      `}</style>
    </>
  );
};

export default TypeModal;
