// src/frontend/poke-query/poke-query-react/src/components/MovesModal.tsx
import React, { useMemo, useState, useId } from 'react';

interface MovesModalProps {
  data: any;
}

const getIdFromUrl = (url: string) => {
  const match = url.match(/\/(\d+)(?!.*\d)/);
  return match ? Number(match[1]) : null;
};

const MovesModal: React.FC<MovesModalProps> = ({ data }) => {
  const modalName = `movesModal-${data.name}`;
  const modalLabel = `${modalName}-Label`;
  const moveData = data.moves || [];
  const [selectedVersion, setSelectedVersion] = useState<string>('');
  const [versionGroups, setVersionGroups] = useState<string[]>([]);
  const [lvlUpMoveData, setLvlUpMoveData] = useState<any[]>([]);
  const [machineMoveData, setMachineMoveData] = useState<any[]>([]);
  const [eggMoveData, setEggMoveData] = useState<any[]>([]);
  const [tutorMoveData, setTutorMoveData] = useState<any[]>([]);
  const [machineMoveDict, setMachineMoveDict] = useState<any[]>([]);

  // Session data
  const sessionVersionGroups = useMemo(() => {
    try {
      const arr = JSON.parse(sessionStorage.getItem('versionGroupData') || '[]');
      return arr.map((x: string) => typeof x === 'string' ? JSON.parse(x) : x);
    } catch {
      return [];
    }
  }, []);
  const sessionMachineData = useMemo(() => {
    try {
      const arr = JSON.parse(sessionStorage.getItem('machineData') || '[]');
      return arr.map((x: string) => typeof x === 'string' ? JSON.parse(x) : x);
    } catch {
      return [];
    }
  }, []);

  // Version group extraction
  React.useEffect(() => {
    const vgs: string[] = [];
    moveData.forEach((x: any) => {
      x.version_group_details.forEach((y: any) => vgs.push(y.version_group.name));
    });
    const unique = [...new Set(vgs)].sort((a, b) => {
      const aId = sessionVersionGroups.find((x: any) => x.name === a)?.id || 0;
      const bId = sessionVersionGroups.find((x: any) => x.name === b)?.id || 0;
      return aId - bId;
    });
    setVersionGroups(unique);
    setSelectedVersion(unique[0] || '');
  }, [moveData, sessionVersionGroups]);

  // Filtering helpers
  const filterBySelectedVersion = (data: any[]) =>
    data.filter((x: any) => {
      x.version_group_details = x.version_group_details.filter(
        (vgd: any) => vgd.version_group.name === selectedVersion
      );
      return x.version_group_details.length > 0;
    });
  const filterByLearnMethod = (data: any[], learnMethod: string) =>
    data.filter((x: any) => {
      x.version_group_details = x.version_group_details.filter(
        (vgd: any) => vgd.move_learn_method.name === learnMethod
      );
      return x.version_group_details.length > 0;
    });

  // Machine lookup
  const getMachine = (move: any) => {
    const machine = sessionMachineData.find(
      (x: any) =>
        getIdFromUrl(x.move.url) === getIdFromUrl(move.move.url) &&
        x.version_group.name === move.version_group_details[0].version_group.name
    );
    return machine?.item?.name || '';
  };

  // Load move data by version
  React.useEffect(() => {
    if (!selectedVersion) return;
    let versionMoveData = filterBySelectedVersion(structuredClone(moveData));
    // For egg moves, use base data if available
    let baseMoveData = versionMoveData;
    setLvlUpMoveData(filterByLearnMethod(structuredClone(versionMoveData), 'level-up'));
    const machineMoves = filterByLearnMethod(structuredClone(versionMoveData), 'machine');
    setMachineMoveData(machineMoves);
    setEggMoveData(filterByLearnMethod(structuredClone(baseMoveData), 'egg'));
    setTutorMoveData(filterByLearnMethod(structuredClone(versionMoveData), 'tutor'));
    // Build machineMoveDict
    setMachineMoveDict(
      machineMoves.map((x: any) => ({ machine: getMachine(x), data: x }))
        .sort((a: any, b: any) => a.machine.localeCompare(b.machine))
    );
    setLvlUpMoveData((arr) => arr.sort((a, b) => a.version_group_details[0].level_learned_at - b.version_group_details[0].level_learned_at));
  }, [selectedVersion, moveData, sessionMachineData]);

  return (
    <>
      {/* Button trigger modal */}
      <button
        type="button"
        className="btn btn-primary mx-1"
        data-bs-toggle="modal"
        data-bs-target={`#${modalName}`}
      >
        Moves
      </button>

      {/* Modal */}
      <div className="modal fade" id={modalName} tabIndex={-1} aria-labelledby={modalLabel} aria-hidden="true">
        <div className="modal-dialog modal-lg modal-dialog-centered modal-dialog-scrollable">
          <div className="modal-content">
            <div className="modal-header">
              <h5 className="modal-title text-capitalize" id={modalLabel}>
                Moves: {data.name}
              </h5>
              <button type="button" className="btn-close" data-bs-dismiss="modal" aria-label="Close" />
            </div>
            <div className="modal-body">
              <div className="container modal-container px-5">
                <label htmlFor="version-select" className="my-0" style={{ display: 'block' }}>Version(s):</label>
                <select
                  id="version-select"
                  className="form-select-lg my-3 mt-1 text-capitalize"
                  aria-label="version group select"
                  value={selectedVersion}
                  onChange={e => setSelectedVersion(e.target.value)}
                >
                  {versionGroups.map(version => (
                    <option className="text-capitalize" value={version} key={version}>
                      {version.replaceAll('-', ' ')}
                    </option>
                  ))}
                </select>

                <div className="accordion" id={`moveModalAccordion-${modalName}`}>
                  {/* Level Up */}
                  <div className="accordion-item">
                    <h2 className="accordion-header" id={`panelsStayOpen-headingOne-${modalName}`}>
                      <button className="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target={`#panelsStayOpen-collapseOne-${modalName}`} aria-expanded="true" aria-controls={`panelsStayOpen-collapseOne-${modalName}`}>
                        Level Up
                      </button>
                    </h2>
                    <div id={`panelsStayOpen-collapseOne-${modalName}`} className="accordion-collapse collapse show" aria-labelledby={`panelsStayOpen-headingOne-${modalName}`}>
                      <div className="accordion-body scrolling-table">
                        <table className="table table-striped table-sm">
                          <thead>
                            <tr>
                              <th scope="col">Move</th>
                              <th scope="col">Level</th>
                            </tr>
                          </thead>
                          <tbody>
                            {lvlUpMoveData.map((move, i) =>
                              move.version_group_details.map((versionGroup: any, j: number) => (
                                <tr key={move.move.name + '-' + i + '-' + j}>
                                  <td className="align-middle text-capitalize">{move.move.name.replace('-', ' ')}</td>
                                  <td className="align-middle">{versionGroup.level_learned_at}</td>
                                </tr>
                              ))
                            )}
                          </tbody>
                        </table>
                      </div>
                    </div>
                  </div>
                  {/* Machine */}
                  <div className="accordion-item">
                    <h2 className="accordion-header" id={`panelsStayOpen-headingTwo-${modalName}`}>
                      <button className="accordion-button collapsed" type="button" id="machineButton" data-bs-toggle="collapse" data-bs-target={`#panelsStayOpen-collapseTwo-${modalName}`} aria-expanded="false" aria-controls={`panelsStayOpen-collapseTwo-${modalName}`}>
                        Machine
                      </button>
                    </h2>
                    <div id={`panelsStayOpen-collapseTwo-${modalName}`} className="accordion-collapse collapse" aria-labelledby={`panelsStayOpen-headingTwo-${modalName}`}>
                      <div className="accordion-body scrolling-table">
                        <table className="table table-striped">
                          <thead>
                            <tr>
                              <th scope="col">Move</th>
                              <th scope="col">TM/HM</th>
                            </tr>
                          </thead>
                          <tbody>
                            {machineMoveDict.map((move, i) => (
                              <tr key={move.data.move.name + '-' + i}>
                                <td className="text-capitalize">{move.data.move.name.replace('-', ' ')}</td>
                                <td>{move.machine.toUpperCase()}</td>
                              </tr>
                            ))}
                          </tbody>
                        </table>
                      </div>
                    </div>
                  </div>
                  {/* Egg */}
                  <div className="accordion-item">
                    <h2 className="accordion-header" id={`panelsStayOpen-headingThree-${modalName}`}>
                      <button className="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target={`#panelsStayOpen-collapseThree-${modalName}`} aria-expanded="false" aria-controls={`panelsStayOpen-collapseThree-${modalName}`}>
                        Egg
                      </button>
                    </h2>
                    <div id={`panelsStayOpen-collapseThree-${modalName}`} className="accordion-collapse collapse" aria-labelledby={`panelsStayOpen-headingThree-${modalName}`}>
                      <div className="accordion-body scrolling-table">
                        <table className="table table-striped">
                          <thead>
                            <tr>
                              <th scope="col">Move</th>
                            </tr>
                          </thead>
                          <tbody>
                            {eggMoveData.map((move, i) => (
                              <tr key={move.move.name + '-' + i}>
                                <td className="text-capitalize">{move.move.name.replace('-', ' ')}</td>
                              </tr>
                            ))}
                          </tbody>
                        </table>
                      </div>
                    </div>
                  </div>
                  {/* Tutor */}
                  <div className="accordion-item">
                    <h2 className="accordion-header" id={`panelsStayOpen-headingFour-${modalName}`}>
                      <button className="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target={`#panelsStayOpen-collapseFour-${modalName}`} aria-expanded="false" aria-controls={`panelsStayOpen-collapseFour-${modalName}`}>
                        Tutor
                      </button>
                    </h2>
                    <div id={`panelsStayOpen-collapseFour-${modalName}`} className="accordion-collapse collapse" aria-labelledby={`panelsStayOpen-headingFour-${modalName}`}>
                      <div className="accordion-body scrolling-table">
                        <table className="table table-striped">
                          <thead>
                            <tr>
                              <th scope="col">Move</th>
                            </tr>
                          </thead>
                          <tbody>
                            {tutorMoveData.map((move, i) => (
                              <tr key={move.move.name + '-' + i}>
                                <td className="text-capitalize">{move.move.name.replace('-', ' ')}</td>
                              </tr>
                            ))}
                          </tbody>
                        </table>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className="modal-footer">
              <button type="button" className="btn btn-primary" data-bs-dismiss="modal">
                Close
              </button>
            </div>
          </div>
        </div>
      </div>
      <style>{`
        .scrolling-table {
          max-height: 25rem;
          width: 100%;
          overflow: auto;
          display: inline-block;
        }
      `}</style>
    </>
  );
};

export default MovesModal;

// src/frontend/poke-query/src/lib/components/modals/MovesModal.svelte
<script>
  // @ts-nocheck

  export let data;

  let modalName = `movesModal-${data.name}`;
  let moveData = data.moves;
  const sessionVersionGroups = JSON.parse(sessionStorage.versionGroupData);
  const sessionMachineData = JSON.parse(sessionStorage.machineData);

  for (let i = 0; i < sessionVersionGroups.length; i++) {
    sessionVersionGroups[i] = JSON.parse(sessionVersionGroups[i]);
  }

  let versionGroups = [];
  let machineMoveDict = [];

  moveData.forEach((x) => {
    x.version_group_details.forEach((y) =>
      versionGroups.push(y.version_group.name)
    );
  });


  versionGroups = [...new Set(versionGroups)].sort(
    (a, b) =>
      sessionVersionGroups.find((x) => x.name === a).id -
      sessionVersionGroups.find((x) => x.name === b).id
  );

  let lvlUpMoveData;
  let machineMoveData;
  let eggMoveData;
  let tutorMoveData;

  const loadMoveDataByVersion = () => {
    let moveDataClone = structuredClone(moveData);

    let versionMoveData = moveDataClone.filter(
      (x) =>
        (x.version_group_details = x.version_group_details.filter(
          (vgd) => vgd.version_group.name === selectedVersion
        ))
    );

    lvlUpMoveData = structuredClone(versionMoveData);
    lvlUpMoveData.forEach(
      (x) =>
        (x.version_group_details = x.version_group_details.filter(
          (vgd) => vgd.move_learn_method.name === "level-up"
        ))
    );
    lvlUpMoveData = lvlUpMoveData
      .filter((x) => x.version_group_details.length > 0)
      .sort(
        (a, b) =>
          a.version_group_details[0].level_learned_at -
          b.version_group_details[0].level_learned_at
      );

    machineMoveData = structuredClone(versionMoveData);
    machineMoveDict = [];
    machineMoveData.forEach(
      (x) =>
        (x.version_group_details = x.version_group_details.filter(
          (vgd) => vgd.move_learn_method.name === "machine"
        ))
    );
    machineMoveData = machineMoveData.filter(
      (x) => x.version_group_details.length > 0
    );
    machineMoveData.forEach((x) => {
      machineMoveDict.push({machine: getMachine(x), data: x});
    });
    machineMoveDict.sort((a, b) => a.machine.localeCompare(b.machine) );

    eggMoveData = structuredClone(versionMoveData);
    eggMoveData.forEach(
      (x) =>
        (x.version_group_details = x.version_group_details.filter(
          (vgd) => vgd.move_learn_method.name === "egg"
        ))
    );
    eggMoveData = eggMoveData.filter((x) => x.version_group_details.length > 0);

    tutorMoveData = structuredClone(versionMoveData);
    tutorMoveData.forEach(
      (x) =>
        (x.version_group_details = x.version_group_details.filter(
          (vgd) => vgd.move_learn_method.name === "tutor"
        ))
    );
    tutorMoveData = tutorMoveData.filter(
      (x) => x.version_group_details.length > 0
    );
  };

  const getMachine = (move) => {
    const machine = sessionMachineData.find((x) => { 
      const moveId = move.move.url.split('/')[4];
      const machineJsonObject = JSON.parse(x);
      const machineMoveUrlId = machineJsonObject.move.url.split('/')[4];
      return machineMoveUrlId === moveId && machineJsonObject.version_group.name === move.version_group_details[0].version_group.name;
     });

    return JSON.parse(machine).item.name;
  };

  let selectedVersion = versionGroups[0];
  loadMoveDataByVersion();
</script>

<!-- Button trigger modal -->
<button
  type="button"
  class="btn btn-primary mx-1"
  data-bs-toggle="modal"
  data-bs-target="#{modalName}"
>
  Moves
</button>

<!-- Modal -->
<div
  class="modal fade"
  id={modalName}
  tabindex="-1"
  aria-labelledby="{modalName}-Label"
  aria-hidden="true"
>
  <div
    class="modal-dialog modal-lg modal-dialog-centered modal-dialog-scrollable"
  >
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title text-capitalize" id="{modalName}-Label">
          Moves: {data.name}
        </h5>
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="modal"
          aria-label="Close"
        />
      </div>
      <div class="modal-body">
        <div class="container modal-container px-5">
          <label for="version-select" class="my-0" style="display: block;">Version(s):</label>
          <select
            id="version-select"
            class="form-select-lg my-3 mt-1 text-capitalize"
            aria-label="version group select"
            bind:value={selectedVersion}
            on:change={() => loadMoveDataByVersion()}
          >
            {#each versionGroups as version}
              <option class="text-capitalize" value={version}>{version.replace('-', ' ')}</option>
            {/each}
          </select>

          <div class="accordion" id="moveModalAccordion-{modalName}">
            <div class="accordion-item">
              <h2
                class="accordion-header"
                id="panelsStayOpen-headingOne-{modalName}"
              >
                <button
                  class="accordion-button"
                  type="button"
                  data-bs-toggle="collapse"
                  data-bs-target="#panelsStayOpen-collapseOne-{modalName}"
                  aria-expanded="true"
                  aria-controls="panelsStayOpen-collapseOne-{modalName}"
                >
                  Level Up
                </button>
              </h2>
              <div
                id="panelsStayOpen-collapseOne-{modalName}"
                class="accordion-collapse collapse show"
                aria-labelledby="panelsStayOpen-headingOne-{modalName}"
              >
                <div class="accordion-body scrolling-table">
                  <table class="table">
                    <thead>
                      <tr>
                        <th scope="col">Move</th>
                        <th scope="col">Level</th>
                      </tr>
                    </thead>
                    <tbody>
                      {#each lvlUpMoveData as move}
                        {#each move.version_group_details as versionGroup}
                          <tr>
                            <td class="text-capitalize">{move.move.name.replace('-', ' ')}</td>
                            <td>{versionGroup.level_learned_at}</td>
                          </tr>
                        {/each}
                      {/each}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
            <div class="accordion-item">
              <h2
                class="accordion-header"
                id="panelsStayOpen-headingTwo-{modalName}"
              >
                <button
                  class="accordion-button collapsed"
                  type="button"
                  id="machineButton"
                  data-bs-toggle="collapse"
                  data-bs-target="#panelsStayOpen-collapseTwo-{modalName}"
                  aria-expanded="false"
                  aria-controls="panelsStayOpen-collapseTwo-{modalName}"
                >
                  Machine
                </button>
              </h2>
              <div
                id="panelsStayOpen-collapseTwo-{modalName}"
                class="accordion-collapse collapse"
                aria-labelledby="panelsStayOpen-headingTwo-{modalName}"
              >
                <div class="accordion-body scrolling-table">
                  <table class="table">
                    <thead>
                      <tr>
                        <th scope="col">Move</th>
                        <th scope="col">TM/HM</th>
                      </tr>
                    </thead>
                    <tbody>
                      {#each machineMoveDict as move}
                        <tr>
                          <td class="text-capitalize">{move.data.move.name.replace('-', ' ')}</td>
                          <td>{move.machine.toUpperCase()}</td>
                        </tr>
                      {/each}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
            <div class="accordion-item">
              <h2
                class="accordion-header"
                id="panelsStayOpen-headingThree-{modalName}"
              >
                <button
                  class="accordion-button collapsed"
                  type="button"
                  data-bs-toggle="collapse"
                  data-bs-target="#panelsStayOpen-collapseThree-{modalName}"
                  aria-expanded="false"
                  aria-controls="panelsStayOpen-collapseThree-{modalName}"
                >
                  Egg
                </button>
              </h2>
              <div
                id="panelsStayOpen-collapseThree-{modalName}"
                class="accordion-collapse collapse"
                aria-labelledby="panelsStayOpen-headingThree-{modalName}"
              >
                <div class="accordion-body scrolling-table">
                  <table class="table">
                    <thead>
                      <tr>
                        <th scope="col">Move</th>
                      </tr>
                    </thead>
                    <tbody>
                      {#each eggMoveData as move}
                        <tr>
                          <td class="text-capitalize">{move.move.name.replace('-', ' ')}</td>
                        </tr>
                      {/each}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
            <div class="accordion-item">
              <h2
                class="accordion-header"
                id="panelsStayOpen-headingFour-{modalName}"
              >
                <button
                  class="accordion-button collapsed"
                  type="button"
                  data-bs-toggle="collapse"
                  data-bs-target="#panelsStayOpen-collapseFour-{modalName}"
                  aria-expanded="false"
                  aria-controls="panelsStayOpen-collapseFour-{modalName}"
                >
                  Tutor
                </button>
              </h2>
              <div
                id="panelsStayOpen-collapseFour-{modalName}"
                class="accordion-collapse collapse"
                aria-labelledby="panelsStayOpen-headingFour-{modalName}"
              >
                <div class="accordion-body scrolling-table">
                  <table class="table">
                    <thead>
                      <tr>
                        <th scope="col">Move</th>
                      </tr>
                    </thead>
                    <tbody>
                      {#each tutorMoveData as move}
                        <tr>
                          <td class="text-capitalize">{move.move.name.replace('-', ' ')}</td>
                        </tr>
                      {/each}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-primary" data-bs-dismiss="modal"
            >Close</button
          >
        </div>
      </div>
    </div>
  </div>
</div>

<style>
  .scrolling-table {
    max-height: 25rem;
    width: 100%;
    overflow: auto;
    display: inline-block;
  }
</style>
